### ISSUE TITLE
文件名生成忽略了{rand:n},这里有个改进版

### ISSUE THREAD

**Issue by edl7878** [springlchy/ueditorgoback#2]
func (this *Uploader) getFullName() string {
	t := time.Now()
	format := this.config["pathFormat"].(string)
	fmt.Println("format:" + format)
	format = strings.Replace(format, "{yyyy}", strconv.Itoa(t.Year()), 1)
	fmt.Println("format:" + format)
	format = strings.Replace(format, "{mm}", strconv.Itoa(int(t.Month())), 1)
	format = strings.Replace(format, "{dd}", strconv.Itoa(t.Day()), 1)
	format = strings.Replace(format, "{hh}", strconv.Itoa(t.Hour()), 1)
	format = strings.Replace(format, "{ii}", strconv.Itoa(t.Minute()), 1)
	format = strings.Replace(format, "{ss}", strconv.Itoa(t.Second()), 1)
	format = strings.Replace(format, "{time}", strconv.FormatInt(t.Unix(), 10), 1)

	reg := regexp.MustCompile("{rand:[0-9]+}")
	randstrs := reg.FindAllString(format, -1)

	randNum := ""
	if len(randstrs) != 0 {
		//只考虑第一个{rand:n}
		reg = regexp.MustCompile("[0-9]+")
		digitNumber, err := strconv.Atoi(reg.FindAllString(randstrs[0], -1)[0])
		if err == nil {
			for i := 1; i <= digitNumber; i++ {
				randNum += strconv.Itoa(rand.Intn(10))
			}
			fmt.Println("randNum:" + randNum)
			format = strings.Replace(format, randstrs[0], randNum, 1)
		}
	}
	//format = format + randNum

	return format + this.getFileExt()
}

**Comment by springlchy** [comment]
是的, 当时想快速测试一下效果,所以没考虑. 真仔细!!  谢谢!!
